substitutions:
  device_description: "Ambilight LED lights"
  name: ambilight
  num_leds: "152"

esphome:
  name: ${name}
  friendly_name: ${name}
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Ambilight Hotspot"
    password: !secret wifi_fallback_password

logger:
  level: INFO

mqtt:
  broker: !secret mqtt_server
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  reboot_timeout: 0s
  birth_message:
    topic: "${name}/sensor/state"
    payload: online
  will_message:
    topic: "${name}/sensor/state"
    payload: offline
  shutdown_message:
    topic: "${name}/sensor/state"
    payload: shutdown

ota:

e131:
  method: multicast
  
text_sensor:
  - platform: version
    name: Ambilight firmware version
    id: firmware_version

light:
  - platform: neopixelbus
    id: ambilight
    type: GRB
    pin: GPIO2
    variant: WS2812
    num_leds: "$num_leds"
    name: "Livingroom Ambilight"
    gamma_correct: 1.5
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - light.control:
            id: ambilight
            effect: "E1.31"
    effects:
      - e131:
          universe: 1
          channels: RGB
      - addressable_rainbow:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
